// db/schema.ts - Drizzle ORM Schema for DDT Chatbot
import { pgTable, varchar, text, timestamp, jsonb, index } from 'drizzle-orm/pg-core';

// Custom vector type for pgvector
const vector = (name: string, _dimensions: number) =>
  text(name).$type<number[]>();

// ============================================
// USERS (linked to Supabase Auth)
// ============================================
export const users = pgTable('users', {
  id: varchar('id', { length: 50 }).primaryKey(), // Supabase Auth UID
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: varchar('name', { length: 255 }),
  role: varchar('role', { length: 20 }).notNull().default('admin'),
  lastLoginAt: timestamp('last_login_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// ============================================
// CHATS (replaces MongoDB sessionId grouping)
// ============================================
export const chats = pgTable('chats', {
  id: varchar('id', { length: 50 }).primaryKey(),
  visitorId: varchar('visitor_id', { length: 100 }), // localStorage session ID
  visitorName: varchar('visitor_name', { length: 255 }),
  visitorEmail: varchar('visitor_email', { length: 255 }),
  status: varchar('status', { length: 20 }).notNull().default('active'),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (table) => ({
  visitorIdx: index('chats_visitor_idx').on(table.visitorId),
  createdAtIdx: index('chats_created_at_idx').on(table.createdAt),
}));

// ============================================
// MESSAGES
// ============================================
export const messages = pgTable('messages', {
  id: varchar('id', { length: 50 }).primaryKey(),
  chatId: varchar('chat_id', { length: 50 }).notNull().references(() => chats.id, { onDelete: 'cascade' }),
  role: varchar('role', { length: 20 }).notNull(), // user, assistant
  content: text('content').notNull(),
  topics: jsonb('topics').notNull().default([]),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (table) => ({
  chatIdx: index('messages_chat_idx').on(table.chatId),
  createdAtIdx: index('messages_created_at_idx').on(table.createdAt),
}));

// ============================================
// KNOWLEDGE SOURCES
// ============================================
export const knowledgeSources = pgTable('knowledge_sources', {
  id: varchar('id', { length: 50 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  type: varchar('type', { length: 20 }).notNull(), // pdf, txt, md, docx, url, text, qa
  status: varchar('status', { length: 20 }).notNull().default('pending'),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (table) => ({
  statusIdx: index('ks_status_idx').on(table.status),
  typeIdx: index('ks_type_idx').on(table.type),
}));

// ============================================
// LEADS (Captured from chat conversations)
// ============================================
export const leads = pgTable('leads', {
  id: varchar('id', { length: 50 }).primaryKey(),
  chatId: varchar('chat_id', { length: 50 }).references(() => chats.id, { onDelete: 'set null' }),
  name: text('name'),
  email: text('email'),
  phone: text('phone'),
  source: varchar('source', { length: 50 }).notNull().default('chat'),
  status: varchar('status', { length: 20 }).notNull().default('new'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (table) => ({
  chatIdx: index('leads_chat_idx').on(table.chatId),
  createdAtIdx: index('leads_created_at_idx').on(table.createdAt),
  emailIdx: index('leads_email_idx').on(table.email),
}));

// ============================================
// DOCUMENT CHUNKS (with vector embedding + full-text search)
// ============================================
export const documentChunks = pgTable('document_chunks', {
  id: varchar('id', { length: 50 }).primaryKey(),
  knowledgeSourceId: varchar('knowledge_source_id', { length: 50 }).notNull().references(() => knowledgeSources.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  embedding: vector('embedding', 1536), // text-embedding-3-small dimensions
  // Full-text search vector - auto-generated by Postgres via GENERATED ALWAYS AS
  // See migration 001_setup_vector.sql for column definition
  searchVector: text('search_vector').$type<string>(), // tsvector (read-only, auto-generated)
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (table) => ({
  ksIdx: index('chunks_ks_idx').on(table.knowledgeSourceId),
}));
